### ISSUE TITLE
Prelaunch Checklist

### ISSUE THREAD

**Issue by VAF-Dev** [Vinny-Frens/Vinny-and-Frens-Contract#1]
1. Payment Splitter to two addresses
2. Configuration for Allowlist
3. Pre-Reveal as minted not a single master switch that turns on
4. Run tests and functions like withdrawal
5. What else?

**Comment by stinkyfi** [comment]
built-in Payment Splitter is passing testing on a 60/40 split.

Please see Request: https://github.com/Vinny-Frens/Vinny-and-Frens-Contract/pull/3
